Repository oghmadev/snomed, pull requests merged in 2018-03, with the labels that each got.

#1 Added docker configuration files
  .env
  Dockerfile
  bin/config/config.ini
  config/environment/development.js
  docker-compose.yml
  package-lock.json
  start.sh
Labels: enhancement

#10 Fixed user privileges when creating files from container
  docker-compose.yml
  start.sh
Labels: bug

#16 api key validation
  api/description/index.js
  api/disorder/index.js
  api/finding/index.js
  api/procedure/index.js
  api/relationship/index.js
  api/sports/index.js
  api/substance/index.js
  bin/data/sql/extensions.sql
  bin/data/sql/indexes.sql
  bin/load_database.py
  components/middleware/index.js
  config/local.env.js
  routes.js
Labels: enhancement, feature

#25 logs hot fix
  app/app.js
  app/components/middleware/index.js
  app/config/express.js
  app/config/logs/common.logger.js
  app/config/logs/express.logger.js
  app/config/logs/snomed.logger.js
Labels: enhancement
